export const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December'
];

export const years = [];
const currentYear = new Date().getFullYear();
for (let i = 1980; i <= currentYear; i++) {
  years.push(i);
}

export const selectedYears = (startingYears, endingYears) => {
  const years = [];
  for (let i = startingYears; i <= endingYears; i++) {
    years.push(i);
  }
  return years;
};

export const normalizeInput = (value, previousValue) => {
  if (!value) return value;

  const currentValue = value.replace(/[^\d]/g, '');
  const cvLength = currentValue.length;

  if (!previousValue || value.length > previousValue.length) {
    if (cvLength < 4) return currentValue;
    if (cvLength < 7) return `(${currentValue.slice(0, 3)}) ${currentValue.slice(3)}`;
    return `(${currentValue.slice(0, 3)}) ${currentValue.slice(3, 6)}-${currentValue.slice(6, 10)}`;
  }
  return currentValue;
};

export const countries = [
  'Afghanistan',
  'Åland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bangladesh',
  'Barbados',
  'Bahamas',
  'Bahrain',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burma',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo-Brazzaville',
  'Congo-Kinshasa',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Curaçao',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'El Salvador',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Federated States of Micronesia',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Lands',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard and McDonald Islands',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn Islands',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Réunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Barthélemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent',
  'Samoa',
  'San Marino',
  'São Tomé and Príncipe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Swaziland',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Vietnam',
  'Venezuela',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];

export const spokenLanguages = [
  'Abkhazian',
  'Afar',
  'Afrikaans',
  'Akan',
  'Albanian',
  'Amharic',
  'Arabic',
  'Aragonese',
  'Armenian',
  'Assamese',
  'Avaric',
  'Avestan',
  'Aymara',
  'Azerbaijani',
  'Bambara',
  'Bashkir',
  'Basque',
  'Belarusian',
  'Bengali',
  'Bihari languages',
  'Bislama',
  'Bosnian',
  'Breton',
  'Bulgarian',
  'Burmese',
  'Catalan, Valencian',
  'Central Khmer',
  'Chamorro',
  'Chechen',
  'Chichewa, Chewa, Nyanja',
  'Chinese',
  'Church Slavonic',
  'Chuvash',
  'Cornish',
  'Corsican',
  'Cree',
  'Croatian',
  'Czech',
  'Danish',
  'Divehi, Dhivehi, Maldivian',
  'Dutch, Flemish',
  'Dzongkha',
  'English',
  'Esperanto',
  'Estonian',
  'Ewe',
  'Faroese',
  'Fijian',
  'Finnish',
  'French',
  'Fulah',
  'Gaelic, Scottish Gaelic',
  'Galician',
  'Ganda',
  'Georgian',
  'German',
  'Gikuyu, Kikuyu',
  'Greek (Modern)',
  'Greenlandic, Kalaallisut',
  'Guarani',
  'Gujarati',
  'Haitian, Haitian Creole',
  'Hausa',
  'Hebrew',
  'Herero',
  'Hindi',
  'Hiri Motu',
  'Hungarian',
  'Icelandic',
  'Ido',
  'Igbo',
  'Indonesian',
  'Interlingue',
  'Inuktitut',
  'Inupiaq',
  'Irish',
  'Italian',
  'Japanese',
  'Javanese',
  'Kannada',
  'Kanuri',
  'Kashmiri',
  'Kazakh',
  'Kinyarwanda',
  'Komi',
  'Kongo',
  'Korean',
  'Kwanyama, Kuanyama',
  'Kurdish',
  'Kyrgyz',
  'Lao',
  'Latin',
  'Latvian',
  'Luxembourgish',
  'Limburgish',
  'Lingala',
  'Lithuanian',
  'Luba-Katanga',
  'Macedonian',
  'Malagasy',
  'Malay',
  'Malayalam',
  'Maltese',
  'Manx',
  'Maori',
  'Marathi',
  'Marshallese',
  'Moldovan, Romanian',
  'Mongolian',
  'Nauru',
  'Navajo, Navaho',
  'Northern Ndebele',
  'Ndonga',
  'Nepali',
  'Northern Sami',
  'Norwegian',
  'Norwegian Nynorsk',
  'Nuosu, Sichuan Yi',
  'Ojibwa',
  'Oriya',
  'Oromo',
  'Ossetian, Ossetic',
  'Pali',
  'Panjabi, Punjabi',
  'Pashto, Pushto',
  'Persian',
  'Polish',
  'Portuguese',
  'Quechua',
  'Romansh',
  'Rundi',
  'Russian',
  'Samoan',
  'Sango',
  'Sanskrit',
  'Sardinian',
  'Serbian',
  'Shona',
  'Sindhi',
  'Sinhala, Sinhalese',
  'Slovak',
  'Slovenian',
  'Somali',
  'Sotho, Southern',
  'South Ndebele',
  'Spanish, Castilian',
  'Sundanese',
  'Swahili',
  'Swati',
  'Swedish',
  'Tagalog',
  'Tahitian',
  'Tajik',
  'Tamil',
  'Tatar',
  'Telugu',
  'Thai',
  'Tibetan',
  'Tigrinya',
  'Tonga (Tonga Islands)',
  'Tsonga',
  'Tswana',
  'Turkish',
  'Turkmen',
  'Twi',
  'Uighur, Uyghur',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Venda',
  'Vietnamese',
  'Volap_k',
  'Walloon',
  'Welsh',
  'Western Frisian',
  'Wolof',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Zhuang, Chuang',
  'Zulu'
];

export const EditLanguages = [
  { value: 'Abkhazian', label: 'Abkhazian' },
  { value: 'Afar', label: 'Afar' },
  { value: 'Afrikaans', label: 'Afrikaans' },
  { value: 'Akan', label: 'Akan' },
  { value: 'Albanian', label: 'Albanian' },
  { value: 'Amharic', label: 'Amharic' },
  { value: 'Arabic', label: 'Arabic' },
  { value: 'Aragonese', label: 'Aragonese' },
  { value: 'Armenian', label: 'Armenian' },
  { value: 'Assamese', label: 'Assamese' },
  { value: 'Avaric', label: 'Avaric' },
  { value: 'Avestan', label: 'Avestan' },
  { value: 'Aymara', label: 'Aymara' },
  { value: 'Azerbaijani', label: 'Azerbaijani' },
  { value: 'Bambara', label: 'Bambara' },
  { value: 'Bashkir', label: 'Bashkir' },
  { value: 'Basque', label: 'Basque' },
  { value: 'Belarusian', label: 'Belarusian' },
  { value: 'Bengali', label: 'Bengali' },
  { value: 'Bihari', label: 'Bihari languages' },
  { value: 'Bislama', label: 'Bislama' },
  { value: 'Bosnian', label: 'Bosnian' },
  { value: 'Breton', label: 'Breton' },
  { value: 'Bulgarian', label: 'Bulgarian' },
  { value: 'Burmese', label: 'Burmese' },
  { value: 'Catalan', label: 'Catalan, Valencian' },
  { value: 'Central', label: 'Central Khmer' },
  { value: 'Chamorro', label: 'Chamorro' },
  { value: 'Chechen', label: 'Chechen' },
  { value: 'Chichewa', label: 'Chichewa, Chewa, Nyanja' },
  { value: 'Chinese', label: 'Chinese' },
  {
    value: 'Church',
    label: 'Church Slavonic, Old Bulgarian, Old Church Slavonic'
  },
  { value: 'Chuvash', label: 'Chuvash' },
  { value: 'Cornish', label: 'Cornish' },
  { value: 'Corsican', label: 'Corsican' },
  { value: 'Cree', label: 'Cree' },
  { value: 'Croatian', label: 'Croatian' },
  { value: 'Czech', label: 'Czech' },
  { value: 'Danish', label: 'Danish' },
  { value: 'Divehi', label: 'Divehi, Dhivehi, Maldivian' },
  { value: 'Dutch', label: 'Dutch, Flemish' },
  { value: 'Dzongkha', label: 'Dzongkha' },
  { value: 'English', label: 'English' },
  { value: 'Esperanto', label: 'Esperanto' },
  { value: 'Estonian', label: 'Estonian' },
  { value: 'Ewe', label: 'Ewe' },
  { value: 'Faroese', label: 'Faroese' },
  { value: 'Fijian', label: 'Fijian' },
  { value: 'Finnish', label: 'Finnish' },
  { value: 'French', label: 'French' },
  { value: 'Fulah', label: 'Fulah' },
  { value: 'Gaelic', label: 'Gaelic, Scottish Gaelic' },
  { value: 'Galician', label: 'Galician' },
  { value: 'Ganda', label: 'Ganda' },
  { value: 'Georgian', label: 'Georgian' },
  { value: 'German', label: 'German' },
  { value: 'Gikuyu', label: 'Gikuyu, Kikuyu' },
  { value: 'Greek', label: 'Greek (Modern)' },
  { value: 'Greenlandic', label: 'Greenlandic, Kalaallisut' },
  { value: 'Guarani', label: 'Guarani' },
  { value: 'Gujarati', label: 'Gujarati' },
  { value: 'Haitian', label: 'Haitian, Haitian Creole' },
  { value: 'Hausa', label: 'Hausa' },
  { value: 'Hebrew', label: 'Hebrew' },
  { value: 'Herero', label: 'Herero' },
  { value: 'Hindi', label: 'Hindi' },
  { value: 'Hiri', label: 'Hiri Motu' },
  { value: 'Hungarian', label: 'Hungarian' },
  { value: 'Icelandic', label: 'Icelandic' },
  { value: 'Ido', label: 'Ido' },
  { value: 'Igbo', label: 'Igbo' },
  { value: 'Indonesian', label: 'Indonesian' },
  { value: 'Interlingue', label: 'Interlingue' },
  { value: 'Inuktitut', label: 'Inuktitut' },
  { value: 'Inupiaq', label: 'Inupiaq' },
  { value: 'Irish', label: 'Irish' },
  { value: 'Italian', label: 'Italian' },
  { value: 'Japanese', label: 'Japanese' },
  { value: 'Javanese', label: 'Javanese' },
  { value: 'Kannada', label: 'Kannada' },
  { value: 'Kanuri', label: 'Kanuri' },
  { value: 'Kashmiri', label: 'Kashmiri' },
  { value: 'Kazakh', label: 'Kazakh' },
  { value: 'Kinyarwanda', label: 'Kinyarwanda' },
  { value: 'Komi', label: 'Komi' },
  { value: 'Kongo', label: 'Kongo' },
  { value: 'Korean', label: 'Korean' },
  { value: 'Kwanyama', label: 'Kwanyama, Kuanyama' },
  { value: 'Kurdish', label: 'Kurdish' },
  { value: 'Kyrgyz', label: 'Kyrgyz' },
  { value: 'Lao', label: 'Lao' },
  { value: 'Latin', label: 'Latin' },
  { value: 'Latvian', label: 'Latvian' },
  { value: 'Letzeburgesch', label: 'Letzeburgesch, Luxembourgish' },
  { value: 'Limburgish', label: 'Limburgish, Limburgan, Limburger' },
  { value: 'Lingala', label: 'Lingala' },
  { value: 'Lithuanian', label: 'Lithuanian' },
  { value: 'Luba', label: 'Luba-Katanga' },
  { value: 'Macedonian', label: 'Macedonian' },
  { value: 'Malagasy', label: 'Malagasy' },
  { value: 'Malay', label: 'Malay' },
  { value: 'Malayalam', label: 'Malayalam' },
  { value: 'Maltese', label: 'Maltese' },
  { value: 'Manx', label: 'Manx' },
  { value: 'Maori', label: 'Maori' },
  { value: 'Marathi', label: 'Marathi' },
  { value: 'Marshallese', label: 'Marshallese' },
  { value: 'Moldovan', label: 'Moldovan, Moldavian, Romanian' },
  { value: 'Mongolian', label: 'Mongolian' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Navajo', label: 'Navajo, Navaho' },
  { value: 'Northern', label: 'Northern Ndebele' },
  { value: 'Ndonga', label: 'Ndonga' },
  { value: 'Nepali', label: 'Nepali' },
  { value: 'Northern', label: 'Northern Sami' },
  { value: 'Norwegian', label: 'Norwegian' },
  { value: 'Norwegian', label: 'Norwegian Bokmål' },
  { value: 'Norwegian', label: 'Norwegian Nynorsk' },
  { value: 'Nuosu', label: 'Nuosu, Sichuan Yi' },
  { value: 'Occitan', label: 'Occitan (post 1500)' },
  { value: 'Ojibwa', label: 'Ojibwa' },
  { value: 'Oriya', label: 'Oriya' },
  { value: 'Oromo', label: 'Oromo' },
  { value: 'Ossetian', label: 'Ossetian, Ossetic' },
  { value: 'Pali', label: 'Pali' },
  { value: 'Panjabi', label: 'Panjabi, Punjabi' },
  { value: 'Pashto', label: 'Pashto, Pushto' },
  { value: 'Persian', label: 'Persian' },
  { value: 'Polish', label: 'Polish' },
  { value: 'Portuguese', label: 'Portuguese' },
  { value: 'Quechua', label: 'Quechua' },
  { value: 'Romansh', label: 'Romansh' },
  { value: 'Rundi', label: 'Rundi' },
  { value: 'Russian', label: 'Russian' },
  { value: 'Samoan', label: 'Samoan' },
  { value: 'Sango', label: 'Sango' },
  { value: 'Sanskrit', label: 'Sanskrit' },
  { value: 'Sardinian', label: 'Sardinian' },
  { value: 'Serbian', label: 'Serbian' },
  { value: 'Shona', label: 'Shona' },
  { value: 'Sindhi', label: 'Sindhi' },
  { value: 'Sinhala', label: 'Sinhala, Sinhalese' },
  { value: 'Slovak', label: 'Slovak' },
  { value: 'Slovenian', label: 'Slovenian' },
  { value: 'Somali', label: 'Somali' },
  { value: 'Sotho', label: 'Sotho, Southern' },
  { value: 'South', label: 'South Ndebele' },
  { value: 'Spanish', label: 'Spanish, Castilian' },
  { value: 'Sundanese', label: 'Sundanese' },
  { value: 'Swahili', label: 'Swahili' },
  { value: 'Swati', label: 'Swati' },
  { value: 'Swedish', label: 'Swedish' },
  { value: 'Tagalog', label: 'Tagalog' },
  { value: 'Tahitian', label: 'Tahitian' },
  { value: 'Tajik', label: 'Tajik' },
  { value: 'Tamil', label: 'Tamil' },
  { value: 'Tatar', label: 'Tatar' },
  { value: 'Telugu', label: 'Telugu' },
  { value: 'Thai', label: 'Thai' },
  { value: 'Tibetan', label: 'Tibetan' },
  { value: 'Tigrinya', label: 'Tigrinya' },
  { value: 'Tonga', label: 'Tonga (Tonga Islands)' },
  { value: 'Tsonga', label: 'Tsonga' },
  { value: 'Tswana', label: 'Tswana' },
  { value: 'Turkish', label: 'Turkish' },
  { value: 'Turkmen', label: 'Turkmen' },
  { value: 'Twi', label: 'Twi' },
  { value: 'Uighur', label: 'Uighur, Uyghur' },
  { value: 'Ukrainian', label: 'Ukrainian' },
  { value: 'Urdu', label: 'Urdu' },
  { value: 'Uzbek', label: 'Uzbek' },
  { value: 'Venda', label: 'Venda' },
  { value: 'Vietnamese', label: 'Vietnamese' },
  { value: 'Volap_k', label: 'Volap_k' },
  { value: 'Walloon', label: 'Walloon' },
  { value: 'Welsh', label: 'Welsh' },
  { value: 'Western', label: 'Western Frisian' },
  { value: 'Wolof', label: 'Wolof' },
  { value: 'Xhosa', label: 'Xhosa' },
  { value: 'Yiddish', label: 'Yiddish' },
  { value: 'Yoruba', label: 'Yoruba' },
  { value: 'Zhuang', label: 'Zhuang, Chuang' },
  { value: 'Zulu', label: 'Zulu' }
];
